FROM alpine:3.22

RUN apk update && apk add --no-cache \
    git \
    ca-certificates \
    openjdk21 \
    maven

ARG github_token

RUN git clone https://${github_token}@github.com/Deepak1125/spring-boot-crud-java.git

WORKDIR /spring-boot-crud-java

RUN mvn clean package

RUN ls target